name: clickable_regions
description: A clickable map of The Netherlands, based on an SVG image.
author: Giovanni Terlingen <me@giovanniterlingen.com>
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  path_parsing: ^0.1.4

  xml: ^4.5.1



dev_dependencies:


dependency_overrides:


flutter:
  uses-material-design: true
  assets:
    - assets/images/hatchback.svg

